[package]
name = "rusty"
version = "0.2.0"
authors = ["Charles <Charles.T.Cheney@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
dotenv = "0.15"
tracing = "0.1.37"
futures = "0.3"
chrono = "0.4.19"
reqwest = {version = "0.11.10", features = ["json"]}
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
serde_json = "1.0"
thiserror = "1.0.37"
base64 = "0.20.0"
poise = "0.5.2"
tokio = {version = "1.22.0", features = ["rt-multi-thread"]}
thousands = "0.2.0"
serde = "1.0.156"
once_cell = "1.17.1"

# shuttle
shuttle-runtime = "0.12.0"
shuttle-poise = "0.12.0"
shuttle-secrets = "0.12.0"