[package]
name = "rusty"
version = "0.1.1"
authors = ["Charles <Charles.Cheney@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2" # needed so intrument works with async functions.
futures = "0.3"
strsim = "0.10.0"
two_timer = "2.2.0"
chrono = "0.4.19"
chrono-tz = "0.5.3"
parse_duration = "2.1.0"
reqwest = {version = "0.11.10", features = ["json"]}
serenity = {version = "0.10.2", features= ["framework", "standard_framework"]}
serde_json = "1.0"
thiserror = "1.0.37"

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread"]

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"