[package]
name = "Rusty"
version = "0.1.0"
authors = ["Charles <Charles.Cheney@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2" # needed so intrument works with async functions.
futures = "0.3"
strsim = "0.10.0"

[dependencies.tokio]
version = "0.2"
features = ["macros", "signal"]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
branch = "current"
features = ["framework", "standard_framework"]